### PR TITLE
Fix a Callable type annotation.

### LINKED ISSUE #65: Failed to `import mart`
```python
Python 3.9.0 (default, Dec  8 2022, 15:50:08)
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import mart
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/weilinxu/coder/MART/mart/__init__.py", line 3, in <module>
    from mart import attack as attack
  File "/home/weilinxu/coder/MART/mart/attack/__init__.py", line 1, in <module>
    from .adversary import *
  File "/home/weilinxu/coder/MART/mart/attack/adversary.py", line 15, in <module>
    from .objective import Objective
  File "/home/weilinxu/coder/MART/mart/attack/objective/__init__.py", line 2, in <module>
    from .classification import *
  File "/home/weilinxu/coder/MART/mart/attack/objective/classification.py", line 25, in <module>
    class RandomTarget(Objective):
  File "/home/weilinxu/coder/MART/mart/attack/objective/classification.py", line 26, in RandomTarget
    def __init__(self, nb_classes: int, gain_fn: Callable[torch.Tensor, torch.Tensor]) -> None:
  File "/home/weilinxu/.pyenv/versions/3.9.0/lib/python3.9/typing.py", line 826, in __getitem__
    raise TypeError(f"Callable[args, result]: args must be a list."
TypeError: Callable[args, result]: args must be a list. Got <class 'torch.Tensor'>
>>>
```

The type annotation has a syntax error. @lumurillo 

I think it should be `Callable[[torch.Tensor, torch.Tensor], torch.Tensor]`.

Why wasn't it captured by the tests?

### PR DESCRIPTION
**Pull request by mzweilin**
# What does this PR do?

Fixes #65

## Type of change

Please check all relevant options.

- [ ] Improvement (non-breaking)
- [x] Bug fix (non-breaking)
- [ ] New feature (non-breaking)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Testing

Please describe the tests that you ran to verify your changes. Consider listing any relevant details of your test configuration.

- [ ] Test A
- [ ] Test B

## Before submitting

- [x] The title is **self-explanatory** and the description **concisely** explains the PR
- [x] My **PR does only one thing**, instead of bundling different changes together
- [ ] I list all the **breaking changes** introduced by this pull request
- [ ] I have commented my code
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have run pre-commit hooks with `pre-commit run -a` command without errors

## Did you have fun?

Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by mzweilin** [comment]
Running `pytest -v` locally does catch the bug that is intentional in [a01f346](https://github.com/IntelLabs/MART/pull/66/commits/a01f34671e5eddc078ed52a85fc46c2dcd674795) . I don't know why CI failed to catch it.

```console
$ pytest -v
=========================================================================== test session starts ===========================================================================
platform linux -- Python 3.9.0, pytest-7.2.0, pluggy-1.0.0 -- /home/weilinxu/coder/MART/.venv/bin/python3.9
cachedir: .pytest_cache
rootdir: /home/weilinxu/coder/MART, configfile: pyproject.toml, testpaths: tests/
plugins: hydra-core-1.2.0, cov-4.0.0
collected 17 items / 16 errors                                                                                                                                            

================================================================================= ERRORS ==================================================================================
________________________________________________________________ ERROR collecting tests/test_adversary.py _________________________________________________________________
tests/test_adversary.py:13: in <module>
    import mart
mart/__init__.py:3: in <module>
    from mart import attack as attack
mart/attack/__init__.py:1: in <module>
    from .adversary import *
mart/attack/adversary.py:15: in <module>
    from .objective import Objective
mart/attack/objective/__init__.py:2: in <module>
    from .classification import *
mart/attack/objective/classification.py:25: in <module>
    class RandomTarget(Objective):
mart/attack/objective/classification.py:26: in RandomTarget
    def __init__(self, nb_classes: int, gain_fn: Callable[torch.Tensor, torch.Tensor]) -> None:
../../.pyenv/versions/3.9.0/lib/python3.9/typing.py:826: in __getitem__
    raise TypeError(f"Callable[args, result]: args must be a list."
E   TypeError: Callable[args, result]: args must be a list. Got <class 'torch.Tensor'>
```

**Comment by lumurillo** [comment]
I haven't been able to reproduce the issue. Can you provide more information about which conditions you got the issue? Which OS, Python version, etc.?

**Comment by mzweilin** [comment]
@lumurillo  
Let's fix the syntax error first and try to improve testing later.

**Review by dxoigmn — APPROVED** [review]
LGTM!

**Pull request merged**
